name: Deploy Symfony to Dev

on:
  workflow_dispatch: # manual trigger only

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup PHP (optional, if you need Composer)
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_mysql
          tools: composer:v2

      # 3. Install dependencies
      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      # 4. Run tests (optional)
      - name: Run tests
        run: |
          if [ -f ./vendor/bin/phpunit ]; then
            ./vendor/bin/phpunit
          else
            echo "⚠️ No tests found"
          fi

      # 5. Deploy files via rsync (no sudo)
      - name: Deploy to Dev Server
        run: |
          rsync -avz --delete \
            -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" \
            ./ ${{ secrets.DEV_USER }}@${{ secrets.DEV_HOST }}:/var/www/html/symfony-demo


